### ISSUE TITLE
execution of goto not updating table id in execution view

### ISSUE THREAD

**Issue by jassoncasey** [flowgrammable/flowsim#60] opened 2015-01-21 18:04 UTC
execution of goto not updating table id in execution view

**Comment by jassoncasey** [comment] 2015-01-23 02:40
The goto label is now getting updated, but the goto instruction should disapear at the same time of updating the table id. Right now it is taking two steps.

**Comment by cchojnacki** [comment] 2015-01-23 16:19
duplicate of https://github.com/flowgrammable/flowsim/issues/72

**Closed by cchojnacki** 2015-01-23 16:19 UTC
Labels: bug
